### ISSUE TITLE
Avoid requiring PyQt5 when just building cli

### ISSUE THREAD

**Issue by jonasnick** [Blockstream/liquid-swap#1]
If I understand correctly, you can't build liquid-swap-cli without requiring PyQt5. In [nix-bitcoin](https://github.com/fort-nix/nix-bitcoin) we're only interested in the cli and try to avoid as many unnecessary dependencies as possible. So it would be nice if in the future we could skip PyQt5 altogether.

**Comment by LeoComandini** [comment]
05bc3593d454fd347e5671feb31fe09f94e01208 should have fixed it. Now `pip install .[CLI]` does not install PyQt5. Upgrading to [0.0.2](https://github.com/Blockstream/liquid-swap/releases/tag/release_0.0.2) should fix the problem.

**Comment by jonasnick** [comment]
perfect, thanks!
