### ISSUE TITLE
Unsupported wallet version with latest elements release

### ISSUE THREAD

**Issue by jonasnick** [Blockstream/liquid-swap#2]
```
[operator@nix-bitcoin:~]$ liquidswap-cli propose 0 0 0 0
liquidswap ERROR Unsupported wallet version, must be at least 169900

[operator@nix-bitcoin:~]$ elements-cli -getinfo
{
  "version": 170001,
  "protocolversion": 70015,
  "walletversion": 130000,
  "balance": {
    "bitcoin": 0.00000000
  },
  "blocks": 1,
  "timeoffset": 0,
  "connections": 2,
  "proxy": "127.0.0.1:9050",
  "difficulty": null,
  "testnet": false,
  "keypoololdest": 1564650968,
  "keypoolsize": 1000,
  "paytxfee": 0.00000000,
  "relayfee": 0.00001000,
  "warnings": ""
}
```
with release https://github.com/ElementsProject/elements/releases/tag/elements-0.17.0.1

**Comment by LeoComandini** [comment]
If the wallet was created with Liquid/Elements 0.14 its version will be unsupported , while newly created wallets have a supported version. A solution is to [upgrade the wallet or move the funds to a new one](https://github.com/Blockstream/liquid-swap/blob/master/docs/faq.md#how-should-i-solve-an-unsupported-wallet-version-error).

This check was added to avoid some issues encountered during the development and to simplify testing. However, if necessary, we may consider to do the efforts to make sure the tool handle also older wallet versions.

**Comment by jonasnick** [comment]
Thank you. Wiping the wallet does work indeed.
